# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad3ae02a4e1cf2e3c9978d678ddecaace187b687a60098cbbe482cdd5a6a80826b14ee38257b8297fa678abab395fbe2c589e0f34d338a997852c122d509cb06

test:
  secret_key_base: 2baba1113ba5b553911537d9f23c53bd4ac647042bfb9d58567797031995240ca019891cf18e352ef65e3f03e8362e7882ae37a6f6c1771e5b98cb42ea1a84c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
